### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by NandyBa** [nebolax/aavealarm#10]
Do you plain to publish a new app release to Apple Store and Google Play ?

**Comment by thegodfatherbeeearth** [comment]
Yep, definitely. I've already made the builds. Now need to do the "paperwork" and add screenshots, etc. to publish

**Comment by NandyBa** [comment]
Note to release a new version it's good to update the screenshots of others put it not a requirements.

**Comment by thegodfatherbeeearth** [comment]
Sorry for the delay. I've just made the release!
